config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from users.apps import UsersConfig
from users.views import user_register_view, user_login_view, user_logout_view, user_profile_view, user_update_view

app_name = UsersConfig.name
urlpatterns = [
    path('', user_login_view, name='login'),
    path('logout/', user_logout_view, name='logout'),
    path('register/', user_register_view, name='register'),
    path('profile/', user_profile_view, name='profile'),
    path('update/', user_update_view, name='update_user'),
]

users/models.py
from django.db import models

from django.contrib.auth.models import AbstractUser

NULLABLE = {'blank': True, 'null': True}


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='email')
    first_name = models.CharField(max_length=150, verbose_name='First Name', default='Anonymous')
    last_name = models.CharField(max_length=150, verbose_name='Last Name', default='Anonymous')
    phone = models.CharField(max_length=35, verbose_name='Phone Number', **NULLABLE)
    telegram = models.CharField(max_length=150, verbose_name='Telegram', **NULLABLE)
    avatar = models.ImageField(upload_to='users/', verbose_name='Avatar', **NULLABLE)
    is_active = models.BooleanField(default=True, verbose_name='Activ')

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def __str__(self):
        return f'{self.email}'

    class Meta:
        verbose_name = 'user'
        verbose_name_plural = 'users'
        # abstract = True # данная модель станет абстрактным базовым классом
        # app_label = 'users' # если модель определена за пределами app., то таким образом можно ее к нему отнести
        # ordering = [-1] # изменение порядка полей в модели
        # proxy = True # модель будет рассматриваться как прокси модель
        # permissions = [] # добавляются группы пользователей которые могут изменять сущность данной модели
        # db_table = 'my_users' # перезаписать имя таблицы в БД
        # get_latest_by = 'birth_date' # возвращает последний объект по порядку возрастания (самый молодой пользователь)

users/forms.py
from django import forms
from django.core.exceptions import ValidationError

from users.models import User
from users.validators import validate_password


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class UserRegisterForm(StyleFormMixin, forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput, min_length=6, max_length=12,
                               help_text='От 6 до 12 букв латинского алфавита и/или цифр')
    password2 = forms.CharField(label='Repeat password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('email', 'avatar',)

    def clean_password2(self):
        temp_data = self.cleaned_data
        validate_password(temp_data['password'])
        if temp_data['password'] != temp_data['password2']:
            print('Пароли не совпадают')
            raise ValidationError('Пароли не совпадают')
        return temp_data['password2']


class UserLoginForm(StyleFormMixin, forms.Form):
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput)


class UserUpdateForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'phone', 'telegram', )

users/views.py
from django.shortcuts import render

from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout

from users.forms import UserRegisterForm, UserLoginForm, UserUpdateForm


def user_register_view(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST, request.FILES)
        if form.is_valid():
            new_user = form.save(commit=False)
            new_user.set_password(form.cleaned_data['password'])
            new_user.save()
            return HttpResponseRedirect(reverse('users:login'))
    return render(request, 'users/register.html', {'form': UserRegisterForm})


def user_login_view(request):
    if request.method == 'POST':
        form = UserLoginForm()
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(email=cd['email'], password=cd['password'])
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return HttpResponseRedirect(reverse('app:index'))  # вместо app имя вашего приложения
                else:
                    return HttpResponse('Аккаунт неактивен!')
    else:
        form = UserLoginForm()
    return render(request, 'users/login.html', {'form': form})


@login_required
def user_profile_view(request):
    user_object = request.user
    context = {
        'user_object': user_object,
        'title': f'Ваш профиль {user_object.first_name}',
    }
    return render(request, 'users/profile.html', context)


@login_required
def user_update_view(request):
    user_object = request.user
    if request.method == 'POST':
        form = UserUpdateForm(request.POST, request.FILES, instance=user_object)
        if form.is_valid():
            user_object = form.save()
            user_object.save()
            return HttpResponseRedirect(reverse('users:profile'))
    context = {
        'user_object': user_object,
        'title': f'Изменить профиль {user_object.first_name}',
        'form': UserUpdateForm(instance=user_object)
    }
    return render(request, 'users/update.html', context)


def user_logout_view(request):
    logout(request)
    return redirect('app:index')

users/templates/users/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{{ title }}</title>
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="{% static 'css/album.css' %}" rel="stylesheet">
</head>

<body>

<header>
    <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
            <div class="row">
                <div class="col-sm-8 col-md-7 py-4">
                    <h4 class="text-white">About</h4>
                    <p class="text-muted">Add some information about the album below, the author, or any other
                        background context. Make it a few sentences long so folks can pick up some informative tidbits.
                        Then, link them off to some social networking sites or contact information.</p>
                </div>
                <div class="col-sm-4 offset-md-1 py-4">
                    <h4 class="text-white">Меню</h4>
                    <ul class="list-unstyled">
                        {% if user.is_authenticated %}
                            <li><a href="{% url 'users:profile' %}" class="text-white">Профиль</a></li>
                            <li><a href="{% url 'users:logout' %}" class="text-white">Выход</a></li>
                        {% else %}
                            <li><a href="{% url 'users:login' %}" class="text-white">Вход</a></li>
                            <li><a href="{% url 'users:register' %}" class="text-white">Регистрация</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="navbar navbar-dark bg-dark box-shadow">
        <div class="container d-flex justify-content-between">
            <a href="#" class="navbar-brand d-flex align-items-center">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none"
                     stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mr-2">
                    <path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"></path>
                    <circle cx="12" cy="13" r="4"></circle>
                </svg>
                <strong>Питомник</strong>
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader"
                    aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
    </div>
</header>
<main role="main">
    <section class="jumbotron text-center">
        <div class="container">
            <h1 class="jumbotron-heading">{{ title }}</h1>
        </div>
    </section>

    <div class="album py-5 bg-light">
        <div class="container">
            {% block content %}
            {% endblock %}


        </div>
    </div>

</main>

<footer class="text-muted">
    <div class="container">
        <p class="float-right">
            <a href="#">Back to top</a>
        </p>
        <p>Album example is &copy; Bootstrap, but please download and customize it for yourself!</p>
        <p>New to Bootstrap? <a href="../../">Visit the homepage</a> or read our <a href="../../getting-started/">getting
            started guide</a>.</p>
    </div>
</footer>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/holder.min.js' %}"></script>
</body>
</html>

users/templates/users/login.html
{% extends 'users/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">Авторизация пользователя</div>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">Вход</button>
                    </form>
                </div>
                <div class="card-footer"></div>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/users/profile.html
{% extends 'users/base.html' %}
{% block content %}
<div class="row">
    <div class="col-3"></div>
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                Мой профиль
            </div>
            <div class="card-body">
                <span class="card-text">Почта: {{user.email}}</span><br>
                <span class="card-text">Имя: {{user.first_name}}</span><br>
                <span class="card-text">Фамилия: {{user.last_name}}</span><br>
                <span class="card-text">Телефон: {{user.phone|default:"Не указано"}}</span><br>
                <span class="card-text">Телеграм-аккаунт: {{user.telegram|default:"Не указано"}}</span><br>
                <button class="btn btn-outline-warning">
                    <a class="btn btn-link" href="{% url 'users:update_user' %}">обновить</a>
                </button>
            </div>
            <div class="card-footer"></div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/register.html
{% extends 'users/base.html' %}

{% block content %}
<div class="row">
    <div class="col-1"></div>
    <div class="col-7">
        <div class="card">
            <div class="card-header">Регистрация нового пользователя</div>
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">Регистрация</button>
                </form>
            </div>
            <div class="card-footer"></div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/update.html
{% extends 'users/base.html' %}

{% block content %}
<div class="row">
    <div class="col-3"></div>
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                Редактирование пользователя
            </div>
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">Сохранить</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}